name: Lambda CI..

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.8", "3.11"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Add repo root to PYTHONPATH
        run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

      - name: Debug PYTHONPATH and directory contents
        run: |
          echo "PYTHONPATH is: $PYTHONPATH"
          echo "Directory Listing:"
          ls -l
          echo "mylambda Listing:"
          ls -l mylambda

      - name: Run tests with coverage
        run: pytest --cov=mylambda tests/

      - name: Show coverage report
        run: coverage report || true  # Show the report, do not fail build on report error
